gsettings set org.gnome.Ptyxis.Shortcuts new-window '<ctrl>n'
gsettings set org.gnome.Ptyxis.Shortcuts new-tab '<ctrl>t'
gsettings set org.gnome.Ptyxis.Shortcuts close-tab '<ctrl>w'
gsettings set org.gnome.Ptyxis.Shortcuts move-tab-left '<ctrl><shift>braceleft'
gsettings set org.gnome.Ptyxis.Shortcuts move-tab-right '<ctrl><shift>braceright'
