gsettings set org.gnome.Ptyxis.Shortcuts new-window '<ctrl>n'
gsettings set org.gnome.Ptyxis.Shortcuts new-tab '<ctrl>t'
gsettings set org.gnome.Ptyxis.Shortcuts close-tab '<ctrl>w'
gsettings set org.gnome.Ptyxis.Shortcuts paste-clipboard '<ctrl>v'
gsettings set org.gnome.Ptyxis.Shortcuts move-previous-tab '<ctrl><shift>bracketleft'
gsettings set org.gnome.Ptyxis.Shortcuts move-next-tab '<ctrl><shift>bracketright'
